name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install server deps
        working-directory: server
        run: |
          npm ci || npm install

      - name: Typecheck
        working-directory: server
        run: npm run typecheck

      - name: Run tests
        working-directory: server
        run: npm run test --if-present


